FROM debian:bookworm-slim

USER root

RUN apt-get update && apt-get install -y \
    curl \
    git \
    nodejs \
    npm \
    python3 \
    python3-pip \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/whyour/qinglong.git /ql

WORKDIR /ql

RUN pip3 install --no-cache-dir \
    Pillow \
    requests \
    beautifulsoup4 \
    imap-tools \
    ddddocr

EXPOSE 5700

CMD ["bash","/ql/docker/docker-entrypoint.sh"]
